//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddOperation {
            get {
                return ResourceManager.GetString("AddOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to questions list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any changes made won&apos;t be saved.
        /// </summary>
        public static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Operation.
        /// </summary>
        public static string CancelOperationTitle {
            get {
                return ResourceManager.GetString("CancelOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while connecting to database.
        /// </summary>
        public static string DataBaseConnectionError {
            get {
                return ResourceManager.GetString("DataBaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection error.
        /// </summary>
        public static string DataBaseConnectionErrortitle {
            get {
                return ResourceManager.GetString("DataBaseConnectionErrortitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to database, refer to your system admin.
        /// </summary>
        public static string DatabaseNotConnectedError {
            get {
                return ResourceManager.GetString("DatabaseNotConnectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not connected.
        /// </summary>
        public static string DatabaseNotConnectedErrorTitle {
            get {
                return ResourceManager.GetString("DatabaseNotConnectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been updated.
        /// </summary>
        public static string DatabaseUpdated {
            get {
                return ResourceManager.GetString("DatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading data please try again.
        ///if you keep getting this error restart the app.
        /// </summary>
        public static string DataFetchingError {
            get {
                return ResourceManager.GetString("DataFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loading Error.
        /// </summary>
        public static string DataFetchingErrorTitle {
            get {
                return ResourceManager.GetString("DataFetchingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading the data.
        /// </summary>
        public static string DataLoadingError {
            get {
                return ResourceManager.GetString("DataLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete question.
        /// </summary>
        public static string DeleteOperationTitle {
            get {
                return ResourceManager.GetString("DeleteOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected questions?.
        /// </summary>
        public static string DeleteQuestionConfirm {
            get {
                return ResourceManager.GetString("DeleteQuestionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to delete the question.
        /// </summary>
        public static string DeleteQuestionError {
            get {
                return ResourceManager.GetString("DeleteQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditOperation {
            get {
                return ResourceManager.GetString("EditOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email format.
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value.
        /// </summary>
        public static string EndValue {
            get {
                return ResourceManager.GetString("EndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value caption.
        /// </summary>
        public static string EndValueCaption {
            get {
                return ResourceManager.GetString("EndValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id value is less than 0.
        /// </summary>
        public static string IdMinusValueError {
            get {
                return ResourceManager.GetString("IdMinusValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string InvalidInputTitle {
            get {
                return ResourceManager.GetString("InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password.
        /// </summary>
        public static string InvalidUserCredintialsError {
            get {
                return ResourceManager.GetString("InvalidUserCredintialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields must have proper values:.
        /// </summary>
        public static string MissingFields {
            get {
                return ResourceManager.GetString("MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received value is null.
        /// </summary>
        public static string NullValueError {
            get {
                return ResourceManager.GetString("NullValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Value.
        /// </summary>
        public static string NullValueErrorTitle {
            get {
                return ResourceManager.GetString("NullValueErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of smileys.
        /// </summary>
        public static string NumberOfSmileys {
            get {
                return ResourceManager.GetString("NumberOfSmileys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars.
        /// </summary>
        public static string NumberOfStars {
            get {
                return ResourceManager.GetString("NumberOfStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed, please try again.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Error.
        /// </summary>
        public static string OperationErrorTitle {
            get {
                return ResourceManager.GetString("OperationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful.
        /// </summary>
        public static string OperationSuccessfulTitle {
            get {
                return ResourceManager.GetString("OperationSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order value is less than 0.
        /// </summary>
        public static string OrderMinusValueError {
            get {
                return ResourceManager.GetString("OrderMinusValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while Loading your page, please try again.
        /// </summary>
        public static string PageLoadingError {
            get {
                return ResourceManager.GetString("PageLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one capital letter and one special character.
        /// </summary>
        public static string PasswordFormatError {
            get {
                return ResourceManager.GetString("PasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at lease 6 characters long.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequiredError {
            get {
                return ResourceManager.GetString("PasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while getting the questions data.
        /// </summary>
        public static string QuestionDataFetchingError {
            get {
                return ResourceManager.GetString("QuestionDataFetchingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question details.
        /// </summary>
        public static string QuestionDetails {
            get {
                return ResourceManager.GetString("QuestionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found.
        /// </summary>
        public static string QuestionNotFoundError {
            get {
                return ResourceManager.GetString("QuestionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question order is required.
        /// </summary>
        public static string QuestionOrderRequiredError {
            get {
                return ResourceManager.GetString("QuestionOrderRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question order must be between 1 and 120.
        /// </summary>
        public static string QuestionOrderValueError {
            get {
                return ResourceManager.GetString("QuestionOrderValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question text can&apos;t be more than 350 characters.
        /// </summary>
        public static string QuestionTextLengthError {
            get {
                return ResourceManager.GetString("QuestionTextLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question text can&apos;t be empty.
        /// </summary>
        public static string QuestionTextRequiredError {
            get {
                return ResourceManager.GetString("QuestionTextRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question type is required.
        /// </summary>
        public static string QuestionTypeError {
            get {
                return ResourceManager.GetString("QuestionTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string RequestProcessingError {
            get {
                return ResourceManager.GetString("RequestProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing fields.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the end value caption field is requried.
        /// </summary>
        public static string SliderEndCaptionRequiredError {
            get {
                return ResourceManager.GetString("SliderEndCaptionRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the end value field must be between 0 and 100.
        /// </summary>
        public static string SliderEndValueNumberError {
            get {
                return ResourceManager.GetString("SliderEndValueNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end value field is required.
        /// </summary>
        public static string SliderEndValueRequiredError {
            get {
                return ResourceManager.GetString("SliderEndValueRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value cannot be greater than end value.
        /// </summary>
        public static string SliderInvalidInput {
            get {
                return ResourceManager.GetString("SliderInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the start value caption field is requried.
        /// </summary>
        public static string SliderStartCaptionRequiredError {
            get {
                return ResourceManager.GetString("SliderStartCaptionRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the start value field must be between 0 and 100.
        /// </summary>
        public static string SliderStartValueNumberError {
            get {
                return ResourceManager.GetString("SliderStartValueNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value field is required.
        /// </summary>
        public static string SliderStartValueRequiredError {
            get {
                return ResourceManager.GetString("SliderStartValueRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smiley faces must be between 2 and 5.
        /// </summary>
        public static string SmileyNumberError {
            get {
                return ResourceManager.GetString("SmileyNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of smiley faces is required.
        /// </summary>
        public static string SmileyRequiredError {
            get {
                return ResourceManager.GetString("SmileyRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database related error, refer to your system admin.
        /// </summary>
        public static string SqlError {
            get {
                return ResourceManager.GetString("SqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string SqlErrorTitle {
            get {
                return ResourceManager.GetString("SqlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of stars must be between 1 and 10.
        /// </summary>
        public static string StarsNumberError {
            get {
                return ResourceManager.GetString("StarsNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of stars is required.
        /// </summary>
        public static string StarsRequiredError {
            get {
                return ResourceManager.GetString("StarsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value.
        /// </summary>
        public static string StartValue {
            get {
                return ResourceManager.GetString("StartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value caption.
        /// </summary>
        public static string StartValueCaption {
            get {
                return ResourceManager.GetString("StartValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Configurator.
        /// </summary>
        public static string SurveyConfiguratorTitle {
            get {
                return ResourceManager.GetString("SurveyConfiguratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text value is null or empty.
        /// </summary>
        public static string TextNullOrEmptyError {
            get {
                return ResourceManager.GetString("TextNullOrEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received token is invalid.
        /// </summary>
        public static string TokenInvalidError {
            get {
                return ResourceManager.GetString("TokenInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string TokenInvalidErrorTitle {
            get {
                return ResourceManager.GetString("TokenInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question type value is incorrect.
        /// </summary>
        public static string TypeValueError {
            get {
                return ResourceManager.GetString("TypeValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access error.
        /// </summary>
        public static string UnAuthorizedAccessError {
            get {
                return ResourceManager.GetString("UnAuthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have restrictions on file operations please refer to your system admin.
        /// </summary>
        public static string UnAuthorizedAccessErrorTitle {
            get {
                return ResourceManager.GetString("UnAuthorizedAccessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unknown error occured.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownErrorTitle {
            get {
                return ResourceManager.GetString("UnknownErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected language isn&apos;t supported.
        /// </summary>
        public static string UnSupportedLanguageError {
            get {
                return ResourceManager.GetString("UnSupportedLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already signed in, sign out first to sign in with another user.
        /// </summary>
        public static string UserAlreadySignedInError {
            get {
                return ResourceManager.GetString("UserAlreadySignedInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be at least 6 characters long.
        /// </summary>
        public static string UserNameLengthError {
            get {
                return ResourceManager.GetString("UserNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string UserNameRequiredError {
            get {
                return ResourceManager.GetString("UserNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
